urls.py
import os

from django.contrib import admin
from django.conf.urls import patterns, url, include
import blog.views
import lectures.views
import common.views

from blog.feeds import *
import rooms.views
import users.views

feeds = {
    'blog': LatestBlogEntries,
}

admin.autodiscover()



urlpatterns = patterns('',
    # Example:
    # (r'^zapisy_zosia/', include('zapisy_zosia.foo.urls')),

     (r'^$', blog.views.index),
     (r'^rooms/$', rooms.views.index),
     (r'^rooms/list.json$', rooms.views.json_rooms_list),
     (r'^rooms/modify/$', rooms.views.modify_room),
     (r'^rooms/open/$', rooms.views.open_room),
     (r'^rooms/close/$', rooms.views.close_room),
     (r'^rooms/trytogetin/$', rooms.views.trytogetin_room),
     (r'^leave_room/$', rooms.views.leave_room),

     (r'^blog/$', blog.views.index),

     # rss feed
     (r'^feeds/$', LatestBlogEntries()),

     # admin related
     (r'^admin/register_payment/$', users.views.register_payment),
     url(r'^admin/', include(admin.site.urls)),
     url(r'^polls/', include('polls.urls', namespace='polls')),
     url(r'^committee/', include('committee.urls', namespace='committee')),

     # registration related
     (r'^register/$', users.views.register),
     (r'^register/thanks/$', users.views.thanks),
     (r'^register/regulations/$', users.views.regulations),

     (r'^register/activate/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', users.views.activate_user),

     (r'^change_preferences/$', users.views.change_preferences),

     # login / logout
     (r'^login/$', common.views.login_view),
     (r'^accounts/login/', common.views.login_view),
     (r'^logout/$', common.views.logout_view),
     (r'^logout/bye/$', common.views.thanks),

     # apps main urls
     (r'^lectures/$', lectures.views.index),
     (r'^program/$', lectures.views.program),

     # static media
     # note, that this should be disabled for production code
	 # (may be disabled outside of django, though)

     # urls required for password change/reset
     (r'^password_change/$', common.views.password_change),
     (r'^password_change/done/$', common.views.password_change_done),

     url(r'^password_reset/$',
         'django.contrib.auth.views.password_reset',
         { 'template_name':'password_reset_form.html' }, name='password_reset'),
     url(r'^password_reset/done/$',
         'django.contrib.auth.views.password_reset_done',
         { 'template_name':'password_reset_done.html' }, name='password_reset_done'),
     url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
         'django.contrib.auth.views.password_reset_confirm',
         { 'template_name':'password_reset_confirm.html' }, name='password_reset_confirm'),
     url(r'^reset/done/$',
         'django.contrib.auth.views.password_reset_complete',
         { 'template_name':'password_reset_complete.html' }, name='password_reset_complete'),
     (r'^static_media/(.*)$', 'django.views.static.serve', {'document_root': os.path.join(os.path.dirname(__file__), 'static_media')})
)
import settings

if settings.DEBUG:
    urlpatterns += patterns('',
#        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#            'document_root': settings.MEDIA_ROOT,
#        }),
        (r'^static_media/(.*)$', 'django.views.static.serve', {'document_root': os.path.join(os.path.dirname(__file__), 'static_media')})
   )

zosiaproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import blog.views
from blog.feeds import *
import lectures.views
import users.views

feeds = {
    'blog': LatestBlogEntries,
}

urlpatterns = [
    url(r'^$', blog.views.index),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^rooms/', include('rooms.urls', namespace='rooms')),

    # rss feed
    url(r'^feeds/$', LatestBlogEntries()),

    # admin related
    url(r'^admin/register_payment/$', users.views.register_payment),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^committee/', include('committee.urls', namespace='committee')),

    # authentication related
    url('^', include('common.urls')),

    # registration related
    url(r'^register/$', users.views.register),
    url(r'^waiting/$', users.views.waiting_list),
    url(r'^register/thanks/$', users.views.thanks),
    url(r'^register/regulations/$', users.views.regulations),

    url(r'^register/activate/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', users.views.activate_user),

    url(r'^change_preferences/$', users.views.change_preferences),

    # apps main urls
    url(r'^lectures/$', lectures.views.index),
    url(r'^agenda/$', include('agenda.urls', namespace='agenda')),
]

users/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin)
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.template import loader, Context
from django.utils import timezone
from django.utils.translation import ugettext as _
from django.utils import timezone
from django.utils.timezone import timedelta

from common.models import ZosiaDefinition

SHIRT_SIZE_CHOICES = (
    ('S', 'S'),
    ('M', 'M'),
    ('L', 'L'),
    ('XL', 'XL'),
    ('XXL', 'XXL'),
    ('XXXL', 'XXXL'),
)

SHIRT_TYPES_CHOICES = (
    ('m', _('klasyczna')),
    ('f', _('żeńska')),
)

BUS_HOUR_CHOICES = (
    ('','obojętne'),
    ('16:00', '16:00'),
    ('18:00', '18:00')
)

BUS_FIRST_SIZE = 0
BUS_SECOND_SIZE = 0


class OrganizationManager(models.Manager):
    def get_organization_choices(self):
        l = [ (org.id, org.name)
               for org in self.get_queryset().filter(accepted=True) ]
        l = l[:20]
        l.append(('new', 'inna'))
        return tuple(l)


class Organization(models.Model):
    name     = models.CharField(max_length=64, default='')
    accepted = models.BooleanField(default=False)

    objects = OrganizationManager()

    class Meta:
        verbose_name = 'Organizacja'
        verbose_name_plural = 'Organizacje'

    def __str__(self):
        return self.name


class ParticipantManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email))

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password)
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Participant(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        _('email address'),
        max_length=254,
        unique=True)
    first_name = models.TextField()
    last_name = models.TextField()
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'),
    )
    date_joined = models.DateTimeField(
        _('date joined'),
        default=timezone.now)
    committee = models.BooleanField(
        _('programme committee'),
        default=False)

    objects = ParticipantManager()

    USERNAME_FIELD = 'email'

    class Meta:
        verbose_name = _('participant')
        verbose_name_plural = _('participants')

    def __str__(self):
        return self.get_full_name()

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        return ' '.join((self.first_name, self.last_name))

    def get_short_name(self):
        "Returns the short name for the user."
        return self.first_name

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email])

    @property
    def is_staff(self):
        return self.is_superuser

    @property
    def has_opened_records(self):
        preference = get_object_or_404(UserPreferences.objects.select_related('state'), user=self)
        user_opening_hour = preference.state.rooming_start - timedelta(minutes=preference.minutes_early)
        return user_opening_hour <= timezone.now() <= preference.state.rooming_final


class UserPreferences(models.Model):
    # This is the only required field
    user = models.OneToOneField(Participant)
    state = models.ForeignKey('common.ZosiaDefinition')
    org = models.ForeignKey(Organization)

    # opłaty
    day_1 = models.BooleanField()
    day_2 = models.BooleanField()
    day_3 = models.BooleanField()

    breakfast_2 = models.BooleanField()
    breakfast_3 = models.BooleanField()
    breakfast_4 = models.BooleanField()

    dinner_1 = models.BooleanField()
    dinner_2 = models.BooleanField()
    dinner_3 = models.BooleanField()

    # inne
    bus         = models.BooleanField(default=False)
    vegetarian  = models.BooleanField()
    paid        = models.BooleanField(default=False)

    shirt_size  = models.CharField(max_length=5, choices=SHIRT_SIZE_CHOICES)
    shirt_type  = models.CharField(max_length=1, choices=SHIRT_TYPES_CHOICES)

    want_bus = models.BooleanField(default=False)

    minutes_early = models.IntegerField(default=0)


    # used to differ from times on which buses leave
    bus_hour = models.CharField(max_length=10, choices=BUS_HOUR_CHOICES, blank=True, null=True, default='')


    photo_url = models.CharField(max_length=250, null=True, blank=True)
    description = models.TextField(_('description'), max_length=2048, blank=True)

    class Meta:
        verbose_name_plural = 'Preferencje'

    def __str__(self):
        return self.user.first_name

    def save(self, *args, **kwargs):
        from common.models import ZosiaDefinition
        # at this moment object probably is different from one in
        # database - lets check if 'paid' field is different
        try:
            old = UserPreferences.objects.get(id=self.id)
            definition = ZosiaDefinition.objects.get(active_definition=True)
            rooming_time = definition.rooming_start
            if self.paid and not old.paid:
                t = loader.get_template('payment_registered_email.txt')
                send_mail( 'Wpłata została zaksięgowana.',
                             t.render(Context({'rooming_time': rooming_time - timedelta(minutes=self.minutes_early)})),
                             None,
                             [ self.user.email ],
                             fail_silently=True )
        except Exception:
            # oh, we're saving for the first time - it's ok
            # move along, nothing to see here
            pass
        super(UserPreferences, self).save(*args, **kwargs)

    @property
    def get_room(self):
        from rooms.models import UserInRoom
        if not hasattr(self, 'user_room'):
            try:
                self.user_room = UserInRoom.objects.get(locator=self.user).room
            except:
                self.user_room = 0
        return self.user_room

    @staticmethod
    def get_free_seats():
        return (BUS_SECOND_SIZE+BUS_FIRST_SIZE - UserPreferences.objects.filter(bus=True).count()) > 0

    @staticmethod
    def get_first_time():
        return (BUS_FIRST_SIZE - UserPreferences.objects.filter(bus=True, bus_hour=BUS_HOUR_CHOICES[1][0]).count()) > 0

    @staticmethod
    def get_second_time():
        return (BUS_SECOND_SIZE - UserPreferences.objects.filter(bus=True, bus_hour=BUS_HOUR_CHOICES[2][0]).count()) > 0

    def bus16_available(self):
        return UserPreferences.objects.filter(bus_hour='16:00').exclude(user=self.user).count() < self.state.bus16_limit

    def bus18_available(self):
        return UserPreferences.objects.filter(bus_hour='18:00').exclude(user=self.user).count() < self.state.bus18_limit

    def count_payment(self):
        # returns how much money user is going to pay
        # hmm, we want to work for preferences, too

        definition = get_object_or_404(ZosiaDefinition, active_definition=True)

        payment = 0

        # payments: overnight stays + board
        if self.day_1 and self.dinner_1 and self.breakfast_2:
            payment += definition.price_overnight_full
        else:
            if self.day_1:
                if self.dinner_1:
                    payment += definition.price_overnight_dinner
                elif self.breakfast_2:
                    payment += definition.price_overnight_breakfast
                else:
                    payment += definition.price_overnight

        if self.day_2 and self.dinner_2 and self.breakfast_3:
            payment += definition.price_overnight_full
        else:
            if self.day_2:
                if self.dinner_2:
                    payment += definition.price_overnight_dinner
                elif self.breakfast_3:
                    payment += definition.price_overnight_breakfast
                else:
                    payment += definition.price_overnight

        if self.day_3 and self.dinner_3 and self.breakfast_4:
            payment += definition.price_overnight_full
        else:
            if self.day_3:
                if self.dinner_3:
                    payment += definition.price_overnight_dinner
                elif self.breakfast_4:
                    payment += definition.price_overnight_breakfast
                else:
                    payment += definition.price_overnight

        # payment: transport
        if self.bus:
            payment += definition.price_transport

        # payment: organization fee
        payment += definition.price_organization
        return payment

    def get_records_time(self):
        return self.state.rooming_start - timedelta(minutes=self.minutes_early)


class Waiting(models.Model):

    user = models.OneToOneField(Participant)
    state = models.ForeignKey('common.ZosiaDefinition')

    day_1 = models.BooleanField()
    day_2 = models.BooleanField()
    day_3 = models.BooleanField()

users/templates/change_preferences.html
{% extends "index.html" %}
{% load i18n %}

{% block css %}
#register_nights, 
#register_breakfasts, 
#register_dinners { 
    display: inline;
}
#register_nights     label,
#register_breakfasts label,
#register_dinners    label { 
    width: 10em;
}
#register_other label {
    display: inline;
    width: 15.3em;
}
.nasty_choices_li label { float: left; }
.nasty_choices_li select { width: 7em; }
}
{% endblock css %}

{% block content %}
{% if user_paid %}
    <ul class="messages">
        {#        <li>{% trans "Paid was registered, see you soon!" %}</li> #}
        <li>Otrzymaliśmy Twoją wpłatę za ZOSIĘ. Jeżeli chcesz dokonać zmian, skontaktuj się z organizatorami.</li>
    </ul>
{% else %}
    {% if payment and not user_paid %}
    <h2>Dane do przelewu</h2>
    <table>
    <tr><td>
<pre>rachunek odbiorcy
tytuł przelewu
imię, nazwisko odbiorcy
adres
miejscowość
kwota
</pre>
    </td><td>
<pre>{{ definition.account_number }}
[ZOSIA{{ year }}] {{user.first_name}} {{user.last_name}}
{{ definition.account_data_1 }}
{{ definition.account_data_2 }}
{{ definition.account_data_3 }}
{{ payment }} zł
    </pre>
    </table>
    <p>
    Potwierdzenie przyjęcia wpłaty zostanie wysłane na&nbsp;Twój adres e-mail.
    </p>
    {% else %}
        <ul class="error_messages">
            <li>{% trans "Musisz zaznaczyć przynajmniej jedną opcję" %}</li>
        </ul>
    {% endif %}
{% endif %}


<h2>{% trans "Preferencje" %}</h2>

<form action="" method="post" id="register_form">{% csrf_token %}
    <fieldset id="register_personal">
        <legend>{% trans "Dane do uwierzytelniania" %}</legend>
        <ol>
            <li>
            <label>e-mail</label>
                {{ user.email }}
            </li>
            <li>
                <label>{% trans "hasło" %}</label>
                <a href="/password_change/">{% trans "zmień" %}</a>
            </li>
        </ol>
    </fieldset>
    <fieldset id="register_personal">
        <legend>{% trans "Dane osobowe" %}</legend>
        <ol>
            <li>
            <label>{% trans "imię" %}, {% trans "nazwisko" %}</label>
                {{ user.first_name }} {{ user.last_name }}
            </li>
            <li>
                {# bw careful with errors here - if there are more than 1 orgs#}
                {% if form.organization_1.errors %}
                <ul class="errorlist">
                {% for error in form.organization_1.errors %}
                    <li>{{error|escape}}</li>
                {% endfor %}
                </ul>
                {% endif %}
                <label for="id_organization_1">
                   {% trans "organizacja" %}
                </label>
                {{ prefs.org }}
            </li>
            {% if pref_form.bus_hour %}
            <li>

            <label>{% trans "bus hour" %}</label> {{ pref_form.bus_hour}}
            </li>
        {% endif %}



        </ol>
    </fieldset>
    <fieldset id="register_nights">
        <legend>{% trans "noclegi" %}</legend>
        <ol>
            {% if pref_form.day_3.errors %}
            <ul class="errorlist">
            {% for error in pref_form.day_3.errors %}
                <li>{{error|escape}}</li>
            {% endfor %}
            </ul>
            {% endif %}
                        <li>
            {{ pref_form.day_1 }} <label for="id_day_1">{% ifequal date_1.month date_2.month %}
                {{ date_1|date:"j" }}/{{ date_2|date:"j E" }}
            {% else %}
                {{ date_1|date:"j E" }} / {{ date_2|date:"j E" }}
            {% endifequal %} </label>
            </li>
            <li>
            {{ pref_form.day_2 }} <label for="id_day_2">{% ifequal date_2.month date_3.month %}
                {{ date_2|date:"j" }}/{{ date_3|date:"j E" }}
            {% else %}
                {{ date_2|date:"j E" }} / {{ date_3|date:"j E" }}
            {% endifequal %} </label>
            </li>
            <li>
            {{ pref_form.day_3 }} <label for="id_day_3">{% ifequal date_3.month date_4.month %}
                {{ date_3|date:"j" }}/{{ date_4|date:"j E" }}
            {% else %}
                {{ date_3|date:"j E" }} / {{ date_4|date:"j E" }}
            {% endifequal %} </label>
            </li>
        </ol>
    </fieldset>
    <fieldset id="register_dinners">
        <legend>{% trans "obiady" %}</legend>
        <ol>
            {% if pref_form.dinner_3.errors %}
            <ul class="errorlist">
            {% for error in form.dinner_3.errors %}<li>{{error|escape}}</li>{% endfor %}
            </ul>
            {% endif %}
            <li>
            {{ pref_form.dinner_1}} <label for="id_dinner_1">{{ date_1|date:"j E" }}</label>
            </li>
            <li>
            {{ pref_form.dinner_2}} <label for="id_dinner_2">{{ date_2|date:"j E" }}</label>
            </li>
            <li>
            {{ pref_form.dinner_3}} <label for="id_dinner_3">{{ date_3|date:"j E" }}</label>
            </li>
        </ol>
    </fieldset>
    <fieldset id="register_breakfasts">
        <legend>{% trans "śniadania" %}</legend>
        <ol>
            {% if form.breakfast_4.errors %}
            <ul class="errorlist">
            {% for error in form.breakfast_4.errors %}<li>{{error|escape}}</li>{% endfor %}
            </ul>
            {% endif %}
            <li>
            {{ pref_form.breakfast_2 }} <label for="id_breakfast_2">{{ date_2|date:"j E" }}</label>
            </li>
            <li>
            {{ pref_form.breakfast_3 }} <label for="id_breakfast_3">{{ date_3|date:"j E" }}</label>
            </li>
            <li>
            {{ pref_form.breakfast_4 }} <label for="id_breakfast_4">{{ date_4|date:"j E" }}</label>
            </li>
        </ol>
    </fieldset>
    <fieldset id="register_other">
        <legend>{% trans "inne" %}</legend>
        <ol>
            <li>
            {{ pref_form.vegetarian }}  <label for="id_vegetarian">{% trans "preferuję kuchnię wegetariańską" %}</label>
            </li>
        {% if pref_form.bus %}
            <li>


                {{ pref_form.bus }}  <label for="id_bus">{% trans "autokar" %}</label>

               <label for="id_bus">{% if definition.bus_is_full %}<strong>UWAGA!</strong> w autobusie skończyły się miejsca. Odznaczenie może skutkować zablokowaniem tej opcji{% endif %} Interesuje mnie zorganizowany transport autokarowym na trasie Wrocław - {{ definition.city }} - Wrocław. Uwaga: autokar wyjeżdża w czwartek</label>

            </li>
        {% else %}
            <li>
                {{ pref_form.want_bus }}
                <label for="id_want_bus">Proszę o wpisanie na listę rezerwową zorganizowanego transportu autokarowego na trasie Wrocław - {{ definition.city }} - Wrocław. Uwaga: autokar wyjeżdża w czwartek</label>
            </li>
        {% endif %}
            <li class="nasty_choices_li">
            {% if pref_form.shirt_size.errors %}
                <ul class="errorlist">
                {% for error in pref_form.shirt_size.errors %}
                    <li>{{error|escape}}</li>
                {% endfor %}
                </ul>
            {% endif %}
            <label for="id_shirt_size">{% trans "koszulka" %}</label> {{ pref_form.shirt_size}}
            </li>
            <li class="nasty_choices_li">
            {% if pref_form.shirt_type.errors %}
                <ul class="errorlist">
                {% for error in pref_form.shirt_type.errors %}
                    <li>{{error|escape}}</li>
                {% endfor %}
                </ul>
            {% endif %}
            <label for="id_shirt_type">{% trans "rodzaj koszulki" %}</label> {{ pref_form.shirt_type}}
            </li>
        </ol>
    </fieldset>

    <fieldset><input type="submit" value="{% trans "Zapisz" %}" /></fieldset>

</form>
{% endblock content %}

{% block right_column %}
<span class="cennik">Cennik</span>

<table>
<tr><td>nocleg:</td><td>{{ definition.price_overnight }}&nbsp;zł</td></tr>
<tr><td>nocleg ze śniadaniem:</td><td>{{ definition.price_overnight_breakfast }}&nbsp;zł</td></tr>
<tr><td>nocleg z obiadokolacją:</td><td>{{ definition.price_overnight_dinner }}&nbsp;zł</td></tr>
<tr><td>nocleg ze śniadaniem i obiadokolacją:</td><td>{{ definition.price_overnight_full }}&nbsp;zł</td></tr>
{% if definition.price_organization %}
    <tr><td>opłata organizacyjna:</td><td>{{ definition.price_organization }}&nbsp;zł</td></tr>
{% endif %}
<tr><td>transport:</td><td>{{ definition.price_transport }}&nbsp;zł</td></tr>
</table>
    
<span><a href="/register/regulations/">Regulamin obozu</a></span>
{% endblock %}

users/templates/reactivation.html
{% extends "index.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans "reactivate" %}</h2>

{% trans "dziękujemy za wizytę"%}

{% endblock %}

users/templates/recover.html
{% extends "index.html" %}

{% block content %}
<h2>Recover your password</h2>

This is outstanding soon-too-be-implemented feature.

{% endblock %}

users/templates/regulations.html
{% extends "index.html" %}
{% load i18n %}
{% block css %}
ol ol
{
	list-style-type: lower-roman;
}
{% endblock css %}


{% block content %}
<h2>{% trans "Regulamin obozu" %}</h2>
<ol>
<li>
Niniejszy regulamin reguluje zasady obowiązujące uczestników
obozu naukowo-rekreacyjnego ZOSIA {{ zosia_final|date:"Y" }}, mającego miejsce w Karpaczu
w dniach {{ zosia_start|date:"d E Y" }} - {{ zosia_final|date:"d E Y" }}, a także definiuje konsekwencje wynikające z nieprzestrzegania tych zasad.
</li>
<li>Organizatorem obozu jest Koło Studentów Informatyki z siedzibą
w Instytucie Informatyki Uniwersytetu Wrocławskiego,
przy ul. Joliot-Curie 15, 50-383 Wrocław.
</li>
<li>Uczestnikami obozu, zwanymi dalej uczestnikami, mogą być jedynie
te osoby zarejestrowane w serwisie internetowym obozu, które uiściły 
odpowiednią opłatę wyliczoną indywidualnie dla każdego uczestnika.
</li>
<li>Obóz rozpoczyna się dnia {{ zosia_start|date:"d E Y" }} i kończy dnia {{ zosia_final|date:"d E Y" }},
jednakże czas pobytu każdego z uczestników jest zależny od jego preferencji 
zadeklarowanych w systemie internetowym.
</li>
<li>W trakcie trwania obozu, uczestnik zobowiązany jest do stosowania się
do poleceń Organizatora i osób przez niego wyznaczonych.
</li>
<li>Nieodpowiednie zachowanie uczestnika w trakcie obozu, w szczególności 
niestosowanie się do poleceń osób wymienionych w pkt. 5, nadużywanie alkoholu,
stosowanie środków odurzających, bądź inne zachowania nieobyczajne, a także
zachowania stwarzające zagrożenie zdrowia i bezpieczeństwa uczestnika
bądź innych uczestników stanowią podstawę do zastosowania następujących
środków dyscyplinujących:
<ol>
<li>upomnienia;</li>
<li>powiadomienia władz organizacji macierzystej (uczelni) o zachowaniu uczestnika;</li>
<li>wydalenia z obozu.</li>
</ol>
<li>O zastosowaniu środka dyscyplinującego, w tym także o rodzaju zastosowanego
środka, decyduje jednoosobowo osoba wskazana przez Organizatora jako Kierownik
obozu. Kierownik obozu może zdecydować o nałożeniu środka najbardziej dotkliwego
bez uprzedniego stosowania pozostałych środków. Kierownik obozu może zdecydować
o zastosowaniu wszystkich środków dyscyplinujących łącznie. Władze uczelni
macierzystych względem osób będących uczestnikami mogą za to samo zachowanie
zastosować kary dyscyplinarne wynikające z Regulaminu Studiów.
</li>
<li>Uczestnik ponosi odpowiedzialność za szkody wyrządzone osobom trzecim
w czasie przebywania na obozie. Organizator nie przejmuje odpowiedzialności
względem osób trzecich za zachowania uczestnika w trakcie obozu. 
</li>
<li>Poprzez swój udział w obozie uczestnik oświadcza względem Organizatora,
iż jest w stanie zdrowia umożliwiającym bezpieczne uczestnictwo w programie obozu. 
</li>
<li>Organizator nie sprawuje pieczy nad osobą uczestnika oraz jego mieniem
w trakcie obozu. W szczególności Organizator nie ponosi odpowiedzialności
za mienie uczestnika pozostawione w obiekcie, w którym organizowany jest obóz.
</li>
<li>Uczestnikowi nie przysługuje zwrot jego świadczenia na rzecz Organizatora
bądź części tego świadczenia w przypadku niepełnego udziału w obozie z przyczyn,
za które Organizator nie odpowiada. W szczególności zwrot świadczenia bądź części
świadczenia nie przysługuje uczestnikowi, względem którego zastosowano karę
przewidzianą w pkt 6.3.
</li>
<li>Warunki rezygnacji:
<ol>
<li>Rezygnacja z imprezy następuje w momencie złożenia przez uczestnika rezygnacji
w formie pisemnej lub elektronicznej na adres pocztowy Organizatora.
</li>
<li>W przypadku rezygnacji potrąca się 100% wpłaconej kwoty.
</li>
<li>Istnieje możliwość zwrotu wpłaconej kwoty, gdy rezygnujący uczestnik znajdzie
na to miejsce innego uczestnika.
</li>
</ol>
</ol>

{% endblock content %}
 

users/templates/thanks.html
{% extends "index.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans "Dziękujemy za rejestrację" %}</h2>

{% trans "Sprawdź pocztę" %}

{% endblock %}

users/templates/the_great_table.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
 "http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>

    <title>ZOSIA 2009 - użytkownicy</title>

    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="Content-Language" content="en,pl">
    <script type="text/javascript">
    <!--
        /* js goes here */
    -->
    </script>
    <style type="text/css">
    <!--
        body  { background-color: white; color: black; }
        xtable {
            border-spacing: 0;
            border-top: 1pt solid black;
            border-left: 1pt solid black;
            border-right: 1pt solid black;
        }
        xtd { border-bottom: 1pt solid black; }
        td { border: 1pt solid black; }
    }
    -->
    </style>
</head>

<body>
    <table>
        <tr>
            <th>nazwisko</th>
            <th>imię</th>
            <th>email</th>
            <th>autobus</th>
            <th>wpłacił</th>
        </tr>
        {% for user,pref in list %}
        <tr>
            <td>{{ user.last_name }} </td>
            <td>{{ user.first_name }} </td>
            <td>{{ user.email }} </td>
            <td>{% if pref.bus %}✓{% endif %}</td>
            <td>{% if pref.paid %}✓{% endif %}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>