urls.py
import os

from django.contrib import admin
from django.conf.urls import patterns, url, include
import blog.views
import lectures.views
import common.views

from blog.feeds import *
import rooms.views
import users.views

feeds = {
    'blog': LatestBlogEntries,
}

admin.autodiscover()



urlpatterns = patterns('',
    # Example:
    # (r'^zapisy_zosia/', include('zapisy_zosia.foo.urls')),

     (r'^$', blog.views.index),
     (r'^rooms/$', rooms.views.index),
     (r'^rooms/list.json$', rooms.views.json_rooms_list),
     (r'^rooms/modify/$', rooms.views.modify_room),
     (r'^rooms/open/$', rooms.views.open_room),
     (r'^rooms/close/$', rooms.views.close_room),
     (r'^rooms/trytogetin/$', rooms.views.trytogetin_room),
     (r'^leave_room/$', rooms.views.leave_room),

     (r'^blog/$', blog.views.index),

     # rss feed
     (r'^feeds/$', LatestBlogEntries()),

     # admin related
     (r'^admin/register_payment/$', users.views.register_payment),
     url(r'^admin/', include(admin.site.urls)),
     url(r'^polls/', include('polls.urls', namespace='polls')),
     url(r'^committee/', include('committee.urls', namespace='committee')),

     # registration related
     (r'^register/$', users.views.register),
     (r'^register/thanks/$', users.views.thanks),
     (r'^register/regulations/$', users.views.regulations),

     (r'^register/activate/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', users.views.activate_user),

     (r'^change_preferences/$', users.views.change_preferences),

     # login / logout
     (r'^login/$', common.views.login_view),
     (r'^accounts/login/', common.views.login_view),
     (r'^logout/$', common.views.logout_view),
     (r'^logout/bye/$', common.views.thanks),

     # apps main urls
     (r'^lectures/$', lectures.views.index),
     (r'^program/$', lectures.views.program),

     # static media
     # note, that this should be disabled for production code
	 # (may be disabled outside of django, though)

     # urls required for password change/reset
     (r'^password_change/$', common.views.password_change),
     (r'^password_change/done/$', common.views.password_change_done),

     url(r'^password_reset/$',
         'django.contrib.auth.views.password_reset',
         { 'template_name':'password_reset_form.html' }, name='password_reset'),
     url(r'^password_reset/done/$',
         'django.contrib.auth.views.password_reset_done',
         { 'template_name':'password_reset_done.html' }, name='password_reset_done'),
     url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
         'django.contrib.auth.views.password_reset_confirm',
         { 'template_name':'password_reset_confirm.html' }, name='password_reset_confirm'),
     url(r'^reset/done/$',
         'django.contrib.auth.views.password_reset_complete',
         { 'template_name':'password_reset_complete.html' }, name='password_reset_complete'),
     (r'^static_media/(.*)$', 'django.views.static.serve', {'document_root': os.path.join(os.path.dirname(__file__), 'static_media')})
)
import settings

if settings.DEBUG:
    urlpatterns += patterns('',
#        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#            'document_root': settings.MEDIA_ROOT,
#        }),
        (r'^static_media/(.*)$', 'django.views.static.serve', {'document_root': os.path.join(os.path.dirname(__file__), 'static_media')})
   )

zosiaproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import blog.views
from blog.feeds import *
import lectures.views
import users.views

feeds = {
    'blog': LatestBlogEntries,
}

urlpatterns = [
    url(r'^$', blog.views.index),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^rooms/', include('rooms.urls', namespace='rooms')),

    # rss feed
    url(r'^feeds/$', LatestBlogEntries()),

    # admin related
    url(r'^admin/register_payment/$', users.views.register_payment),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^committee/', include('committee.urls', namespace='committee')),

    # authentication related
    url('^', include('common.urls')),

    # registration related
    url(r'^register/$', users.views.register),
    url(r'^waiting/$', users.views.waiting_list),
    url(r'^register/thanks/$', users.views.thanks),
    url(r'^register/regulations/$', users.views.regulations),

    url(r'^register/activate/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', users.views.activate_user),

    url(r'^change_preferences/$', users.views.change_preferences),

    # apps main urls
    url(r'^lectures/$', lectures.views.index),
    url(r'^agenda/$', include('agenda.urls', namespace='agenda')),
]

lectures/models.py
from django.conf import settings

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class LectureManager(models.Manager):

    def create_lecture(self, new_data, user):
        data = new_data.cleaned_data
        lecture = self.model( author    = user,
                              title     = data['title'],
                              duration  = data['duration'],
                              abstract  = data['abstract'],
                              # sprezentujpl_email = data['sprezentujpl_email'], 
                              info      = data['info'],
                              date_time = timezone.now(),
                              accepted  = False
                            )
        lecture.save()
        return lecture


type_choices = ((0, 'Wykład'), (1, 'Warsztaty'))
person_type_choices = ((0, 'Sponsor'), (1, 'Gość'), (2, 'Normalny'))


class Lecture(models.Model):
    title     = models.CharField(max_length=256)
    duration  = models.PositiveIntegerField(choices=[(5,5), (15,15),(20,20),(25,25),(30,30), (100,'inne')])
    abstract  = models.TextField(max_length=768)
    info      = models.TextField(max_length=2048, blank=True)
    type        = models.IntegerField(choices=type_choices, verbose_name='Typ zajęć', default=0)
    person_type = models.IntegerField(choices=person_type_choices, verbose_name='Typ wykładowcy', default=2)


    description = models.TextField(max_length=2048, blank=True, verbose_name='Opis')
    author    = models.ForeignKey(settings.AUTH_USER_MODEL)
    author_show = models.CharField(max_length=256, null=True, blank=True)
    date_time = models.DateTimeField(auto_now_add=True)
    for_committe = models.BooleanField(default=True, verbose_name='Dla komitetu programowego')
    accepted  = models.BooleanField(default=False)

    order = models.IntegerField(default=99)

    objects = LectureManager()

    class Meta:
        verbose_name = 'Wykład'
        verbose_name_plural = 'Wykłady'
        ordering = ['order', 'id']

    def __str__(self):
        return "{} - {}".format(self.author, self.title)

lectures/forms.py
# -*- coding: UTF-8 -*-

from django import forms
from lectures.models import Lecture


class LectureForm(forms.ModelForm):
    class Meta:
        fields = ('title', 'duration', 'abstract', 'info')
        model = Lecture

lectures/views.py
# -*- coding: UTF-8 -*-

from django.utils.translation import ugettext as _
from django.shortcuts import render

from common.helpers import *

from .forms import *


def index(request):
    title = "Lectures"
    sponslectures = Lecture.objects.filter(accepted=True, person_type=0).order_by('order')
    lectures = Lecture.objects.filter(accepted=True, person_type__gte=1).order_by('person_type', 'order')
    lectures_null = Lecture.objects.filter(accepted=True, person_type__gte=1).order_by('person_type', 'order')
    if request.user.is_authenticated():
        my_lectures = Lecture.objects.filter(author=request.user)

    workshops = Lecture.objects.filter(accepted=True, person_type__gte=1, type=1).order_by('person_type', 'order')
    if is_lecture_suggesting_enabled():
        if request.user.is_authenticated() and request.user.is_active:
            lecture_proposition_form = LectureForm(request.POST or None)
            if lecture_proposition_form.is_valid():
                lecture = lecture_proposition_form.save(commit=False)
                lecture.author = request.user
                lecture.save()
                messages = [ _("thankyou") ]
                lecture_proposition_form = LectureForm()

    return render(request, 'lectures.html', locals())

lectures/templates/lectures.html
{% extends "index.html"%}
{% load i18n %}

{% block css %}

.lecture p, #lecture_abstract {
	text-indent: 1.5em;
	text-align: justify;
	text-justify: inter-word;
	text-align-last: left;
	max-width: 45em;
}
strong.lecture_author + p { text-indent: 0; }
#lecture_author { margin-bottom: 2px;}
#lecture_abstract { margin-bottom: 5px;text-indent: 0;}
#lecture_time { margin-bottom: 1em;}
#note {
    color: #444444;
    font-family: 'Lucida Grande','Trebuchet MS',Verdana,Helvetica,Arial,sans-serif;
    font-size: 11px;
}

article.even aside { margin-top: 8px; margin-right: 10px; float:left; }
article.odd aside { margin-top: 8px; margin-left: 10px; float:right; }

.author_description {font-style: italic; text-indent:0!important; }

article { border-bottom: 1px solid #efefef;}

    article { margin-bottom: 25px; min-height:160px}
article.even div {margin-left: 130px;width: 550px;}
article.odd div {margin-left: 10px;width: 550px;}
article.normal p {max-width: 57em;}
article.normal  {min-height: 0;}






{% endblock css %}

{% block content %}

{% if messages %}
    <ul class="messages">
        {% for msg in messages %}
        {% blocktrans %}<li>{{ msg }}</li>{% endblocktrans %}
        {% endfor %}
    </ul>
{% endif %}
{% if lecture_proposition_form.errors %}
    <ul class="error_messages">
        <li>{% trans "Repair errors below, please." %}</li>
    </ul>
{% endif %}

{% comment %}

<h2>{% trans "Invited talks" %}</h2>

<article class="lecture_special">
	<h3>Tytuł</h3>
	<div id="lecture_author">Autor</div>
	<div id="lecture_abstract">Abstrakt</div>
</article>

{% endcomment %}



{% if sponslectures %}
<h2>Wykłady sponsorów</h2>

    {% include 'show_lecture.html' with lectures=sponslectures %}
{% endif %}

    {% if lectures %}
    <h2>Wykłady uczestników</h2>
     {% include "show_lecture.html" with lectures=lectures %}
      {% else %}
        <p>
        {% trans "Nie opublikowaliśmy jeszcze wykładów." %}</label>
        </p>
    {% endif %}



{% if not messages %}
    {% if my_lectures %}
        <h2>Twoje propozycje</h2>
        <ul>
        {% for lecture in my_lectures %}
        <li>
            <h3>{{ lecture.title }}</h3>
            <p>{{ lecture.duration }}</p>
            <p>{{ lecture.abstract }}</p>
            <p>{{ lecture.info }}</p>
        </li>
        {% endfor %}
        </ul>
    {% endif %}
{% if lecture_proposition_form %}
<h2>{% trans "Suggest your lecture" %}</h2>
    <form action="." method="post">{% csrf_token %}
    <fieldset>
    <legend>{% trans "Public info" %}</legend>
        <ol>
            <li>
                {% if lecture_proposition_form.title.errors %}
                <ul class="errorlist">
                {% for error in lecture_proposition_form.title.errors %}
                    <li>{{error|escape}}</li>
                {% endfor %}
                </ul>
                {% endif %}
            <label for="id_title">{% trans "Title" %}</label>
            {{ lecture_proposition_form.title }}
            </li>
            <li>
                {% if lecture_proposition_form.duration.errors %}
                <ul class="errorlist">
                {% for error in lecture_proposition_form.duration.errors %}
                    <li>{{error|escape}}</li>
                {% endfor %}
                </ul>
                {% endif %}
            <label for="id_duration">{% trans "duraszatan" %}<span>{% trans "inminutes" %}</span></label>
            {{ lecture_proposition_form.duration }}
            </li>
            <li>
                {% if lecture_proposition_form.abstract.errors %}
                <ul class="errorlist">
                {% for error in lecture_proposition_form.abstract.errors %}
                    <li>{{error|escape}}</li>
                {% endfor %}
                {% endif %}
                <label for="id_abstract">{% trans "Abstract" %}<span>{% trans "(max chars)" %}</span></label>
            {{ lecture_proposition_form.abstract }}
            </li>
        </ol>
    </fieldset>
    <fieldset>
    <legend>{% trans "Additional information" %}</legend>
        <ol>
            <li>
                {% if lecture_proposition_form.info.errors %}
                <ul class="errorlist">
                {% for error in lecture_proposition_form.info.errors %}
                    <li>{{error|escape}}</li>
                {% endfor %}
                </ul>
                {% endif %}
                <label for="id_info">{% trans "Your suggestions, requests and comments intended for organizers and a lot more, what you always wanted to say these philistinic bastards with purulent knees" %}</label>
                {{ lecture_proposition_form.info }}
            </li>
         </ol>
    </fieldset>
    <p><input type="submit" value="{% trans "Suggest" %}" /></p>
    </form>

{% endif %}
{% endif %}

{% endblock content %}

{% block right_column %}
{% if user.is_authenticated %}
    <h2>{% trans "Yes we can" %}</h2>
    <p>{% trans "Hurray" %}</p>
{% else %}
    <h2>{% trans "Ops, youre not logged in" %}</h2>
    <p>{% trans "You have to be registered" %}</p>
{% endif %}
{% endblock right_column %}

lectures/templates/program.html
{% extends "index.html" %}
{% load i18n %}

{% block css %}

    .lecture p, #lecture_abstract {
    text-indent: 1.5em;
    text-align: justify;
    text-justify: inter-word;
    text-align-last: left;
    max-width: 45em;
    }
    strong.lecture_author + p { text-indent: 0; }
    #lecture_author { margin-bottom: 2px;}
    #lecture_abstract { margin-bottom: 5px;text-indent: 0;}
    #lecture_time { margin-bottom: 1em;}
    #note {
    color: #444444;
    font-family: 'Lucida Grande','Trebuchet MS',Verdana,Helvetica,Arial,sans-serif;
    font-size: 11px;
    }

    div.program {background: #fff; display: block;}
    .cell_text1{margin-left: 10px; display:inline; }
    .cell_text2{margin-left: 10px; display:inline; }
    .cell_text3{margin-left: 30px; display:inline; }
    div.cell_part_hour {margin-left: 30px; display: inline;}
    div.cell_hour {display: inline; margin-top:10px;}
    div.cell_hour_1 {display: inline; margin-left:6px;}

{% endblock css %}

{% block content %}

<h3>27.02.2014 r. (Czwartek)</h3>
<div>
	<div>20:00 – 21:30</div><div>Obiadokolacja</div>
</div>
<br>
<div style="margin-bottom:8px">
        <div><div>21:30 – 21:40</div><div>Oficjalne rozpoczęcie <strong>ZOSI 2014</strong></div></div>
	<br>
	<div><div>21:40 – 22:10</div><div><strong>Maciej Piróg</strong>, <i>W (ko)indukcyjne (ko)ło, Macieju</i></div></div>
	<div><div>22:15 – 22:35</div><div><strong>Janusz Dziemidowicz</strong>, <i>Skąd się biorą bitcoiny?</i></div></div>
	<div><div>22:40 - 23:10</div><div><strong>Maciej Kotowicz</strong>, <i>Łoboże kradną mi pieniądze</i></div></div>
	<div><div>23:15 – 00:00</div><div><strong>Hans de Nivelle</strong>, <i>Richard Wagner</i></div></div>
</div>
<br><br>
<h3>28.02.2014 r. (Piątek)</h3>
<div>
	<div><div>07:30 – 09:30</div><div>Śniadanie</div></div>
</div>
<br>
<div style="margin-bottom:8px">
	<div><div>16:00 – 16:20</div><div><strong>Linda Smug</strong>, <i>Praktyczna strona edukacji</i></div></div>
	<div><div>16:25 – 16:40</div><div><strong>Aleksander Szymanek</strong>, <i>Projekty zespołowe w warunkach uniwersyteckich...</i></div></div>
	<div><div>16:45 – 17:00</div><div><strong>Kryspina Konopko</strong>, <i>Upiór pod klawiaturą. Demonologia w grach RPG.</i></div></div>
	<div><div>17:05 - 17:35</div><div><strong>Tomasz Piasecki</strong>, <i>Mam lagi w kryształowej kuli, czyli ezoteryka kontra rzeczywistość nowych technologii</i></div></div>
	<div><div>17:40 – 17:55</div><div><strong>Łukasz Dobrowolski</strong>, <i>Efekt fotoelektryczny czyli jak działają aparaty cyfrowe.</i></div></div>


<div style="margin-bottom:8px">
	<div><div>17:30 – 19:00</div><div>Obiadokolacja</div></div>
</div>

<div style="margin-bottom:8px">
	<div><div>19:00 – 20:30</div><div><strong>(Capgemini) Jarosław Ratajski</strong>, <i>HTML5 + CSS3. Co powinieneś już dawno o technologiach webowych wiedzieć, a o czym najprawdopodobniej nie miałeś pojęcia</i></div></div>
<br>
    <div><div>20:45 - 21:15</div><div><strong>Kacper Górski</strong>, <i>Nie mam czasu! Muszę otagować fszystkich na fejsbuku!</i></div></div>
    <div><div>21:20 – 21:35</div><div><strong>Maciej Jabłoński</strong>, <i>Zapisy nie działają!</i></div></div>
    <div><div>21:40 - 21:55</div><div><strong>Anna Piekarska</strong>, <i>Fakty I mity o komputerze kwantowym</i></div></div>
    <br>
</div>
<div style="margin-bottom:8px">
    <div><div>22:10 - 22:40</div><div><strong>Filip Chudy</strong>, <i>Jak kazać układom scalonym scalać</i></div></div>
    <div><div>22:45 - 23:00</div><div><strong>Wiktor Mociun</strong>, <i>LinuX Containers i Chef</i></div></div>
    <div><div>23:05 - 23:20</div><div><strong>Mateusz Bajorski</strong>, <i>Zerowakonfiguracja - poznaj swoich sąsiadów</i></div></div>
    <div><div>23:25 – 00:00</div><div><strong>Adam “Nitro” De.</strong>, <i>Grafika komputerowa dla mas, nie dla klas!</i></div></div>
</div>
<br><br>
<h3>01.03.2014 r. (Sobota)</h3>
<div>
	<div><div>07:30 – 09:30</div><div>Śniadanie</div></div>
</div>
<br>
<div style="margin-bottom:8px">
    <div><div>16:00 -17:00</div><div><strong>(Neurosoft) Cezary Dołęga</strong>, <i>Homo Cyberneticus -- czyli dokąd zmierza sztuczna inteligencja</i></div></div>
    <div><div>17:15 - 17:45</div><div><strong>Michał Ryszard Balicki</strong>, <i>Arimaa – rozrywka dla ludzi, wyzwanie dla komputerów</i></div></div>
	<div><div>17:50 - 18:05</div><div><strong>Kinga Mielcarska</strong>, <i>Do you hear what I hear? Ultrasound detectors in bat research</i></div></div>
</div>
<div style="margin-bottom:8px">
	<div><div>17:30 - 19:00</div><div>Obiadokolacja</div></div>
</div>
<div style="margin-bottom:8px">
	<div><div>19:00 - 19:20</div><div><strong>Jakub Michaliszyn</strong>, <i>Konstruktorzy do świń!</i></div></div>
	<div><div>19:25 - 19:45</div><div><strong>Björn Pelzer</strong>, <i>Towards Cognitive Automated Reasoning</i></div></div>
	<div><div>19:50 - 20:20</div><div><strong>Arkadiusz Flinik</strong>, <i>ReactJS</i></div></div>
	<br>
	<div><div>20:35 - 21:05</div><div><strong>Paweł Hałdrzyński</strong>, <i>OMG!!!!11 web-pwned!</i></div></div>
	<div><div>21:10 - 21:40</div><div><strong>Jakub Stępniewicz</strong>, <i>Co tak brumi?</i></div></div>
	<div><div>21:45 - 22:15</div><div><strong>Krzysztof Nowicki</strong>, <i>Krótka historia Javy</i></div></div>
	<br>
	<div><div>22:30 - 23:00</div><div><strong>Anna Stożek</strong>, <i>Uran od A jak a-bomb, do S jak sztuka.</i></div></div>
	<div><div>23:05 - 23:35</div><div><strong>Dariusz Jackowski</strong>, <i>Między techniką, nauką i sztuką, czyli co robi informatyk w państwowej instytucji kultury</i></div></div>
</div>
<br>
<br>
<h3>02.03.2014 r. (Niedziela)</h3>
<div>
<div><div>07:30 – 09:30</div><div>Śniadanie</div></div>
<div><div>12:30</div><div>Wyjazd z ośrodka</div></div>
</div>
<br><br><br><br><br><br><br><br>
<br>
</div>
{% endblock content %}